### PR TITLE
create readme.md

### LINKED ISSUE #12: Improve the Readme file
Edit the Readme.md file to be more descriptive of what shiftboard is about.

### PR DESCRIPTION
**Pull request by EmeraldEntities**
Closes #12.

Hopefully, this README is sufficient enough for now.

### CODE REVIEW

**Comment by shari09** [comment]
I'm not hosting it on my pc for v0.1 🙂

**Review by shari09 — CHANGES_REQUESTED** [review]
idk man maybe u can host it and leave ur computer on all night 😌

**Comment by EmeraldEntities** [comment]
mAybE I wiLl

**Review by shari09 — APPROVED** [review]
tHen dO iT

**Pull request merged**
